package com.example.guessandlearn;

public class English_normal_question {
    public static String question[] ={
            "How do you pronounce the word \"drought\"?",
            "What is the correct way to pronounce the word \"indict\"?",
            "How do you say the word \"urchin\"?",
            "What is the correct pronunciation of the word \"bologna\"?",
            "How do you say the word \"mauve\"?",
            "What is the correct way to pronounce the word \"colonel\"?",
            "How do you say the word \"chassis\"?",
            "What is the correct pronunciation of the word \"laboratory\"?",
            "How do you pronounce the word \"plaid\"?",
            "What is the correct way to say the word \"worcestershire\"?",
            "How do you say the word \"hierarchy\"?",
            "What is the correct way to pronounce the word \"glacier\"?",
            "How do you say the word \"clique\"?",
            "What is the correct pronunciation of the word \"debris\"?",
            "How do you say the word \"quay\"?",
            "What is the correct way to pronounce the word \"solder\"?",
            "How do you pronounce the word \"turbulence\"?",
            "What is the correct pronunciation of the word \"mischievous\"?",
            "How do you say the word \"verdant\"?",
            "What is the correct way to pronounce the word \"epitome\"?",
            "How do you say the word \"draught\"?",
            "What is the correct pronunciation of the word \"sauté\"?",
            "How do you pronounce the word \"valet\"?",
            "What is the correct way to pronounce the word \"flaccid\"?",
            "How do you say the word \"faux\"?",
            "What is the correct pronunciation of the word \"queue\"?",
            "How do you say the word \"ennui\"?",
            "What is the correct way to pronounce the word \"gauge\"?",
            "How do you say the word \"lingerie\"?",
            "What is the correct pronunciation of the word \"crêpe\"?"
    };

    public static String choices[][] = {
            {"DROW-tuh", "DROUT", "DRUFF-tuh", "DRAWT"},
            {"in-DICK-t", "in-DYT", "in-DEET", "in-DITE"},
            {"UR-kin", "ER-shin", "UR-shen", "UH-shin"},
            {"buh-LO-nee", "ba-LO-nya", "bo-LO-nya", "bu-LO-nya"},
            {"MAHV", "MOHV", "MOWV", "MUHV"},
            {"kur-nl", "kuhr-nel", "kuhr-nl", "kur-nel"},
            {"chass-iss", "chas-see", "cha-see", "chass-ee"},
            {"LAB-ruh-tor-ee", "LAB-ruh-tree", "lah-BOR-uh-tor-ee", "LAB-ruh-tory"},
            {"played", "plad", "plade", "plaid"},
            {"wuh-ster-sheer", "wur-ster-shy-er", "woos-ter-shur", "wur-ches-ter-shy-er"},
            {"HIE-ruh-kee", "hie-RAHR-kee", "hi-ER-ark-ee", "HI-er-ar-key"},
            {"GLAY-shur", "GLAY-see-er", "GLAY-shee-er", "GLAY-syur"},
            {"kleek", "click", "clee-kay", "kleek-ay"},
            {"duh-BREE", "day-BREE", "dee-BREE", "deb-ris"},
            {"kee", "kway", "kwey", "kwee"},
            {"SOD-er", "SOL-der", "SAWL-der", "SUL-der"},
            {"TUR-byu-luhns", "TUR-buh-lens", "TUR-bu-luhnce", "TUR-bu-lents"},
            {"MIS-chiv-us", "mis-CHEEV-ee-us", "mis-CHEE-vee-us", "mis-CHIV-ee-us"},
            {"VER-dent", "VER-dont", "ver-DANT", "ver-dahn"},
            {"ih-PIT-uh-mee", "ee-PIT-ohm", "ep-i-TOWM", "ep-i-TOHM"},
            {"draft", "drowt", "drawt", "drot"},
            {"soh-TAY", "SAW-tay", "soh-TAYE", "saw-TAYE"},
            {"val-ay", "va-LET", "va-LAY", "val-et"},
            {"FLAK-sid", "FLA-sid", "FLA-sayd", "FLA-kid"},
            {"foe", "focks", "fow", "faw"},
            {"kyoo", "kwee", "kway", "kyew"},
            {"ON-wee", "EN-wee", "EN-nyoo-ee", "AHN-wee"},
            {"gaj", "gayj", "gayzh", "gawj"},
            {"lahn-jer-ay", "ling-ger-ee", "lawn-jer-ay", "lahn-jer-ee"},
            {"kreyp", "krep", "krape", "krep-ay"}
    };

    public static String correctAnswers[] = {
            "DROW-tuh",
            "in-DYTE",
            "UR-chin",
            "buh-LO-nya",
            "MOHV",
            "kur-nel",
            "chas-see",
            "LAB-ruh-tree",
            "plaid",
            "wur-ster-shy-er",
            "HIE-ruh-kee",
            "kuhr-nel",
            "kleek",
            "deb-ris",
            "kee",
            "SOD-er",
            "TUR-byu-luhns",
            "MIS-chiv-us",
            "VER-dant",
            "ih-PIT-uh-mee",
            "draft",
            "soh-TAY",
            "va-LAY",
            "FLAK-sid",
            "foe",
            "kyoo",
            "ON-wee",
            "gayj",
            "ling-ger-ee",
            "krep"
    };
}
